Hustle_24/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
# from rest_framework import routers
from shop import views as shop_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from watched_products import views as watched_products_views




# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),

    path('', include('user_sessions.urls', namespace='user_sessions')),

    path('', include('shop.urls', namespace='shop')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('carts.urls', namespace='carts')),
    path('', include('watched_products.urls', namespace='watched_products')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path('register', views.registerCustomer, name="register"),
    path('register/vendor/', views.registerVendor, name="register-vendor"),
    
    path('login/', views.loginPage, name='login'),
    # path('login/', views.LoginView.as_view(), name='login'),

    path('logout/', views.logoutUser, name='logout'),

    path('customer/<customer>', views.customerPage, name='customer'),
    path('vendor/<vendor>', views.vendorPage, name='vendor'),
    path('account/', views.accountSettings, name='account'),

    path("password_reset", views.password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html", success_url=reverse_lazy(
        'accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),      
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers
# from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt import views as jwt_views



app_name= 'api'
router = routers.DefaultRouter()
router.register(r'Products', ListProductsView)
router.register(r'Categories', CategoriesView)
router.register(r'Product-photos', ProductImageView)
router.register(r'Reviews', ReviewsView)
router.register(r'Shop', ShopView)
router.register(r'Specifications', ProductSpecificationView)
# router.register(r'Registration', RegistrationView)


urlpatterns = [
	path('', include(router.urls)),
	path('sign-up/', RegistrationView.as_view(), name='register'),
	path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]
# urlpatterns+= router.urls

shop/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import  views

app_name= 'shop'

urlpatterns = [
    path('', views.home,name="home"),
    # path('shop/<shop>', views.shop, name='shop'),
    path('<shop>/product/<ref_code>/<title>/', views.productDetail, name='product'),    
    path('<shop>/product/add', views.addProduct, name='addProduct'),
    path('<shop>/<product>/<id>/edit/', views.editProduct, name='editProduct'), 
    path('updatephoto', views.deleteProductImage,name="updatephoto"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/views.py
import datetime
import json
from orders.forms import *
from carts.models import *
from carts.utils import *
from django.contrib import messages
from django.contrib.auth import (authenticate, get_user_model, login, logout,
								 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from shop.models import *
from orders.models import *
from .decorators import *
from .forms import *
from .models import *
from django.http import JsonResponse, HttpResponse
from django.contrib.auth import views as auth_views
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm
# from django.contrib.auth.models import User
from django.conf import settings
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes




User = get_user_model()
Now = datetime.now()


def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					email_template_name = "accounts/password/password_reset_email.txt"
					c = {
					"email": user.email,
					'domain': get_current_site(request),
					'site_name': 'Website',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
					email = render_to_string(email_template_name, c)
					try:
						send_mail(subject, email, settings.EMAIL_HOST_USER , [user.email], fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					return redirect("password_reset/done/")
			else:
				messages.warning(request, 'Email does not exist!')
	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="accounts/password/password_reset.html", context={"password_reset_form":password_reset_form})



@unauthenticated_user
@with_usertype(allowed_roles=['Vendor','bami'])
def registerCustomer(request):
	form = CreateUserForm()
	if request.method == "POST":
		form = CreateUserForm(request.POST)
		username = request.POST.get('username')
		email = request.POST.get('email')
		password = request.POST.get('password1')
		password_confirmation = request.POST.get('password2')
		print("Hello, ",request.POST,request.POST.get('password'), form.is_valid())
		if form.is_valid():
			# Here, you would save the user or perform other actions
			new_user = User.objects.create_user(username=username,password=password,email=email)
			new_user.save()
			messages.success(request, 'Account was created for ' + username)
			return redirect('accounts:login')
		else:
			# If form is not valid, add errors to the message framework
			for field, errors in form.errors.items():
				for error in errors:
					messages.error(request, f"Error in {field}: {error}")
					print(error)
			return render(request, 'accounts/index.html', {'form': form})
	context = {'form': form}
	return render(request, 'accounts/index.html', context)

@with_usertype(allowed_roles=['Customer'])
def registerVendor(request):
	if request.user.is_anonymous:
		return redirect('accounts:login')
	else:
		if request.user.is_customer and request.user.is_vendor == False:
			user = User.objects.get(id=request.user.id)
			user.is_vendor = True
			user.save()
			Vendor.objects.create(
				user=request.user,
				username=request.user.username,
				email=request.user.email,
				firstname=request.user.first_name,
				lastname=request.user.last_name
			)
			return redirect(f'/vendor/{request.user.username}')
		else:
			form = CreateUserForm()
			if request.method == "POST":
				firstname = request.POST.get('firstname')
				lastname = request.POST.get('lastname')
				email = request.POST.get('email')
				password = request.POST.get('password')
				print("Hello, ",request.POST,request.POST.get('password'))
				if password:			
					username = firstname + " " + lastname
					new_user = User.objects.create_user(username= username,
														email=email,
														password=password,
														first_name=firstname,
														last_name = lastname,
														is_vendor=True,
														)
					new_user.save()
					messages.success(request,'Account and Shop was created for ' + username)
					return redirect('accounts:login')
			context = {'form': form}
	return render(request, 'accounts/register_vendor.html', context)

@unauthenticated_user
def loginPage(request):
	form = AccountAuthenticationForm(request.POST or None)
	if request.POST:
		email = request.POST.get('email')
		password = request.POST.get('password')
		if form.is_valid():
			user =  authenticate(email=email, password=password)
			print('here1', user.username)
			if user:
				login(request, user)
				messages.success(request, "Logged In")
				print('hopefully')
				return redirect(f'/customer/{email}',)
		else:
			messages.info(request, 'Username OR password is incorrect')				
	return render(request,'accounts/signin.html', {'form': form })
	
def logoutUser(request):
	messages.add_message(request, messages.INFO, '{0} logged out.'.format(request.user))
	logout(request)
	return redirect('accounts:login')

	
# vendor/bami
@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['Customer'])
def customerPage(request,customer):
	customer = request.user.customer
	vendor = request.user.vendor if request.user.is_vendor else ""
	carts = []
	data = cartData(request)
	cart_data = data['cart_data']
	cart_items = data['cart_items']
	customerAddresses = ShippingAddress.objects.filter(customer=customer)
	customerPayments = ShippingPayment.objects.filter(customer=customer)
	customerCarts = Cart.objects.filter(customer=customer)
	# print(customerPayments)
	# for payments in customerPayments:
	# 	print(payments.name_on_card)
	for cart in customerCarts:
		cart_details = {'cart':
								{
									'ref_code': cart.ref_code,
									'cart_items': cart.get_cart_items(),
									'is_ordered': cart.complete,
									'quantity': cart.quantity,
									'get_cart_items_total_quantity': cart.get_cart_items_total_quantity(),
									'get_cart_total_price': cart.get_cart_total_price(),
								}
						}
		carts.append(cart_details)
	carts.reverse()
	userPicture = request.user.customer.profile_pic.url
	customerForm = CustomerForm(instance=customer)
	passwordChangeForm = ChangeUserPasswordForm(instance=request.user)
	shippingAddressForm = ShippingAddressForm(instance=customer)
	shippingPaymentForm = ShippingPaymentForm()
	pictureForm = ChangePictureForm()
	username = (f"{customer.firstname} {customer.lastname}").title()
	username = username if bool(username.strip()) else customer.username
	print(request.POST,"Customer Page",  request.POST.get("form_type"),request.FILES)
	if request.method == "POST" and request.POST.get("form_type") == 'accountSetting':
		customerForm = CustomerForm(request.POST, request.FILES, instance=customer)
		if customerForm.is_valid():
			customerForm.save()
			updated_request = request.POST.copy()
			updated_request.update({'first_name': request.POST['firstname'], "last_name": request.POST['lastname']})
			userForm = UserForm(updated_request, request.FILES, instance=request.user)
			if userForm.is_valid():
				userForm.save()

			if request.user.is_vendor:
				vendorForm = VendorForm(request.POST, request.FILES, instance=vendor)
				if vendorForm.is_valid():
					vendorForm.save()

	elif request.method == "POST" and request.POST.get("form_type") == 'passwordChange':
		passwordChangeForm = ChangeUserPasswordForm(request.POST, request.FILES,instance=request.user)
		if passwordChangeForm.is_valid():
			passwordChangeForm.save()
			update_session_auth_hash(request, request.user)
	elif request.method == "POST" and request.POST.get("form_type") == 'AddressAdded':
		shippingAddressForm = ShippingAddressForm(request.POST, request.FILES,instance=customer)
		print(ShippingAddressForm,request.POST)
		if shippingAddressForm.is_valid():
			print("erere")
			for address in customerAddresses:
				address.active = False
				address.save()
			new_address = ShippingAddress()
			new_address.customer = customer
			new_address.address = ShippingAddressForm.cleaned_data['address']
			new_address.city = ShippingAddressForm.cleaned_data['city']
			new_address.state = ShippingAddressForm.cleaned_data['state']
			new_address.zipcode = ShippingAddressForm.cleaned_data['zipcode']
			new_address.active = True
			new_address.save()
			print(new_address)
	elif request.method == "POST" and request.POST.get("form_type") == 'PaymentAdded':
		shippingPaymentForm = ShippingPaymentForm(request.POST, request.FILES,instance=customer)
		if shippingPaymentForm.is_valid():
			print("ererepayment")
			if customerPayments.exists():
				for payment in customerPayments:
					payment.active = False
					payment.save()
			new_payment = ShippingPayment()
			new_payment.customer = customer
			new_payment.card_number = ShippingPaymentForm.cleaned_data['card_number']
			new_payment.name_on_card = ShippingPaymentForm.cleaned_data['name_on_card']
			new_payment.expiry_month = ShippingPaymentForm.cleaned_data['expiry_month']
			new_payment.expiry_year = ShippingPaymentForm.cleaned_data['expiry_year']
			new_payment.security_code = ShippingPaymentForm.cleaned_data['security_code']
			new_payment.active = True
			new_payment.save()
			print(new_payment)
	elif request.method == "POST" and request.POST.get("form_type") == 'ActivatePayment':
		for payment in customerPayments:
			payment.active = False

accounts/templates/accounts/index.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Create an account</title>
		<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, user-scalable=no"
		/>
		<link
			href="https://fonts.googleapis.com/css?family=Karla:400,700&amp;display=swap"
			rel="stylesheet"
		/>
		<link rel="stylesheet" href="{% static 'css/app.css' %}" />
		<style>
			/* Styling for error message popups */
			.error-message {
				position: fixed;
				top: 20px;
				right: 20px;
				background-color: #ff4c4c;
				color: white;
				padding: 15px;
				border-radius: 5px;
				box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
				z-index: 9999;
				display: none; /* Initially hidden */
				font-size: 14px;
			}

			.error-message.show {
				display: block;
				animation: fadeIn 0.5s ease;
			}

			/* Fade-in animation */
			@keyframes fadeIn {
				0% {
					opacity: 0;
					transform: translateX(10px);
				}
				100% {
					opacity: 1;
					transform: translateX(0);
				}
			}
		</style>
	</head>
	<body>
		<div class="page">
			<!-- Error message container -->
			<div id="error-messages" class="error-message"></div>

			<div style="display: grid">
				<form class="form" method="POST">
					{% csrf_token %}
					<div class="form__container">
						<div class="logo">
							<a href="{% url 'shop:home' %}">
								<img
									class="logo__pic"
									src="{% static 'images/favicon_io/android-chrome-192x192.png' %}"
									width="80"
								/>
							</a>
						</div>
						<div class="fieldset">
							<div class="field">{{ form.username }}</div>
							<div class="field">{{ form.email }}</div>
							<div class="field">{{ form.password1 }}</div>
							<div class="field">{{ form.password2 }}</div>
						</div>
						<button type="submit" class="btn">Sign up</button>
						<div class="text">
							By creating an account, you agree and accept our
							<a href="#">Terms</a> and
							<a href="#">Privacy Policy</a>.
						</div>
					</div>
					<div class="form__footer">
						Already have an account?
						<a href="{% url 'accounts:login' %}">Log in</a>.
					</div>
				</form>
			</div>
			<!-- <div class="about"></div> -->
		</div>

		<script>
			// Function to display error messages as pop-ups
			function showErrorMessages(errors) {
			  const errorContainer = document.getElementById('error-messages');
			  let errorMessages = '';

			  // Format the errors into a string
			  errors.forEach(function (error) {
			    errorMessages += `<p>${error}</p>`;
			  });

			  // Display the error messages in the container
			  errorContainer.innerHTML = errorMessages;

			  // Show the error pop-up
			  errorContainer.classList.add('show');

			  // Hide the error message after 5 seconds
			  setTimeout(function () {
			    errorContainer.classList.remove('show');
			  }, 5000);
			}

			// Example usage in Django template: show errors passed from view
			{% if form.errors %}
			  var errors = [];
			  {% for field, error_list in form.errors.items %}
			    {% for error in error_list %}
			      errors.push("{{ error }}");
			    {% endfor %}
			  {% endfor %}
			  showErrorMessages(errors);
			{% endif %}
		</script>
	</body>
</html>

accounts/templates/accounts/login.html
{% extends 'shop/main.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}	

<div class="image image-overlay" style="background-image:url({% static '/images/pexels-allan-so-2622170.jpg' %})">
</div>
{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
  {% for error in form.non_field_errors %}
	{{ error }}
  {% endfor %}
</div>
{% endif %}
<div class="container">
	<div class="row justify-content-center align-items-center vh-md-100">
		<div class="col-md-10 col-lg-5">
			<div class="accordion accordion-portal" id="accordionExample">
				<div class="card">
					<div class="card-header" id="headingOne">
						<h2 class="mb-0 p-3 border-bottom">Sign In</h2>
					</div>

					<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
						<form action="" method="POST">
							<div class="card-body">
								<div class="row mt-2">
									{% csrf_token %}
									<div class="form-group col-12">
										<label for="email1">Email</label>
										<input type="text" name="email" class="form-control" id="email1">
									</div>
									<div class="form-group col-12 mt-1">
										<label for="password1">Password</label>
										<input type="password"  name="password" class="form-control" id="password1">
									</div>
									<input type="hidden" name="customer" value="True" />
									<div class="col-12 mt-2">
										<input class="btn btn-block btn-primary" type="submit" value="sign In" style="box-shadow: none;box-shadow: none;width: 100%;padding: 11px 0 30px 0;" >
									</div>
								</div>
							</div>
						</form>
						<div class=" d-flex justify-content-center links col-12 my-3" style="padding: 5px 0;">
							<small class="small">
								Don't have an account ? <a href="{% url 'accounts:customer_signup' %}" class=" ml-2 eyebrow">Sign-Up</a>
							</small>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
<!-- <h1>Registration page</h1> -->

<form action="" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<div class=" d-flex justify-content-center mt-3 login_container">
		<input class="btn login_btn" type="submit" value="Register">
	</div>
</form>

<div class=" mt-4">
	<div class=" d-flex justify-content-center links">
		Already have an account <a href="{% url 'login' %}" class=" ml-2">Login</a>
	</div>
</div>

accounts/templates/accounts/register_customer.html
{% extends 'shop/main.html' %}
{% block title %}Sign-up{% endblock %}
{% load static %}
{% block content %}	

<div class="image image-overlay" style="background-image:url({% static '/images/pexels-allan-so-2622170.jpg' %})">
</div>
{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
  {% for error in form.non_field_errors %}
	{{ error }}
  {% endfor %}
</div>
{% endif %}
<div class="container py-8">
	<div class="row justify-content-center align-items-center vh-md-100">
		<div class="col-md-10 col-lg-5">
			<div class="accordion accordion-portal" id="accordionExample">
				<div class="card" style="padding: 0;">
					<div class="card-header" id="headingOne">
						<h2 class="mb-0 p-3 border-bottom">Sign Up</h2>
					</div>

					<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
						<form action="" method="POST">
							<div class="card-body">
								<div class="row mt-2">
									{% csrf_token %}
									<div class="form-group col-12">
										<label for="firstname1">Firstname</label>
										<input type="text" name="firstname" class="form-control" id="firstname1">
									</div>
									<div class="form-group col-12">
										<label for="lastname1">Lastname</label>
										<input type="text" name="lastname" class="form-control" id="lastname1">
									</div>
									<div class="form-group col-12">
										<label for="username1">Username</label>
										<input type="text" name="username" class="form-control" id="username1">
									</div>
									<div class="form-group col-12">
										<label for="Email1">Email</label>
										<input type="email" name="email" class="form-control" id="email">
									</div>
									<div class="form-group col-12 mt-1">
										<label for="password1">Password</label>
										<input type="password"  name="password" class="form-control" id="password1">
									</div>
									<div class="form-group col-12 mt-1">
										<label for="password2">Password Confermation</label>
										<input type="password"  name="password" class="form-control" id="password2">
									</div>
									<!-- <input type="hidden" name="customer" value="True" /> -->
									<div class="col-12 mt-2">
										<input class="btn btn-block btn-primary" type="submit" value="sign up" style="box-shadow: none;box-shadow: none;width: 100%;padding: 11px 0 30px 0;" >
									</div>
								</div>
								
							</div>
							<div class=" d-flex justify-content-center links col-12 my-3" style="padding: 5px 0;">
								<small class="small">
									Already have an account ? <a href="{% url 'accounts:login' %}" class=" ml-2 eyebrow">Sign-In</a>
								</small>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/register_vendor.html
{% extends 'shop/main.html' %}
{% block title %}Shop{% endblock %}
{% load static %}
{% block content %}	

<div class="image image-overlay" style="background-image:url({% static '/images/pexels-nice-guys-757432.jpg' %})">
</div>
{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
  {% for error in form.non_field_errors %}
	{{ error }}
  {% endfor %}
</div>
{% endif %}
<div class="container py-8">
	<div class="row justify-content-center align-items-center vh-md-100">
		<div class="col-md-10 col-lg-5">
			<div class="accordion accordion-portal" id="accordionExample">
				<div class="card" style="padding: 0;">
					<div class="card-header" id="headingOne">
						<h2 class="mb-0 p-3 border-bottom">Sign Up - Setup Shop</h2>
					</div>

					<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
						<form action="" method="POST">
							<div class="card-body">
								<div class="row mt-2">
									{% csrf_token %}
									<div class="form-group col-12">
										<label for="firstname1">Firstname</label>
										<input type="text" name="firstname" class="form-control" id="firstname1">
									</div>
									<div class="form-group col-12">
										<label for="lastname1">Lastname</label>
										<input type="text" name="lastname" class="form-control" id="lastname1">
									</div>
									<div class="form-group col-12">
										<label for="Email1">Email</label>
										<input type="email" name="email" class="form-control" id="email">
									</div>
									<div class="form-group col-12 mt-1">
										<label for="password1">Password</label>
										<input type="password"  name="password" class="form-control" id="password1">
									</div>
									<div class="form-group col-12 mt-1">
										<label for="password2">Password Confermation</label>
										<input type="password"  name="password" class="form-control" id="password2">
									</div>
									<!-- <input type="hidden" name="customer" value="True" /> -->
									<div class="col-12 mt-2">
										<input class="btn btn-block btn-primary" type="submit" value="sign up" style="box-shadow: none;box-shadow: none;width: 100%;padding: 11px 0 30px 0;" >
									</div>
								</div>
								
							</div>
							<div class=" d-flex justify-content-center links col-12 my-3" style="padding: 5px 0;">
								<small class="small">
									Already have an account ? <a href="{% url 'accounts:login' %}" class=" ml-2 eyebrow">Sign-In</a>
								</small>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>




{% endblock %}

accounts/templates/accounts/signin.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Create an account</title>
		<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, user-scalable=no"
		/>
		<link
			href="https://fonts.googleapis.com/css?family=Karla:400,700&amp;display=swap"
			rel="stylesheet"
		/>
		<link rel="stylesheet" href="{% static 'css/app.css' %}" />
	</head>
	<body>
		<div class="page page_login">
			<form class="form" method="POST">
				{% csrf_token %}
				<div class="form__container">
					<div class="logo">
						<a href="{% url 'shop:home' %}"
							><img
								class="logo__pic"
								src="{% static 'images/favicon_io/android-chrome-192x192.png' %}"
								width="80"
						/></a>
					</div>
					<div class="fieldset">
						<div class="field">{{ form.email }}</div>
						<div class="field">{{ form.password }}</div>
					</div>
					<button type="submit" class="btn">Sign in</button>
					<div class="text">
						Can’t remember your password?
						<a href="{% url 'accounts:password_reset' %}"
							>Recover it</a
						>.
					</div>
				</div>
				<div class="form__footer">
					Don't Have an Account?
					<a href="{% url 'accounts:register' %}">Create it</a>.
				</div>
			</form>
			<div class="about"></div>
		</div>
	</body>
</html>