Hustle_24/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
# from rest_framework import routers
from shop import views as shop_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from watched_products import views as watched_products_views




# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),

    path('', include('user_sessions.urls', namespace='user_sessions')),

    path('', include('shop.urls', namespace='shop')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('carts.urls', namespace='carts')),
    path('', include('watched_products.urls', namespace='watched_products')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path('register', views.registerCustomer, name="register"),
    path('register/vendor/', views.registerVendor, name="register-vendor"),
    
    path('login/', views.loginPage, name='login'),
    # path('login/', views.LoginView.as_view(), name='login'),

    path('logout/', views.logoutUser, name='logout'),

    path('customer/<customer>', views.customerPage, name='customer'),
    path('vendor/<vendor>', views.vendorPage, name='vendor'),
    path('account/', views.accountSettings, name='account'),

    path("password_reset", views.password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html", success_url=reverse_lazy(
        'accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),      
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers
# from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt import views as jwt_views



app_name= 'api'
router = routers.DefaultRouter()
router.register(r'Products', ListProductsView)
router.register(r'Categories', CategoriesView)
router.register(r'Product-photos', ProductImageView)
router.register(r'Reviews', ReviewsView)
router.register(r'Shop', ShopView)
router.register(r'Specifications', ProductSpecificationView)
# router.register(r'Registration', RegistrationView)


urlpatterns = [
	path('', include(router.urls)),
	path('sign-up/', RegistrationView.as_view(), name='register'),
	path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]
# urlpatterns+= router.urls

carts/urls.py
from django.urls import path

from . import views

app_name ='carts'

urlpatterns = [
    path('cart', views.cart,name="cart"),

    path('cart/add', views.addItem,name="add"),
    path('cart/remove', views.removeItem,name="remove"),
    path('cart/status', views.status, name="status"),
    path('cart/remove-all', views.removeAllItems, name="removeAll"),

    # path('cart/messages', views.send_messages, name="messages"),
    path('cart/checkout/auth', views.checkout_authentication,name="checkout_auth"),
    path('cart/checkout/location', views.checkout_location,name="checkout_location"),

    path('cart/process-order', views.processOrder,name="process-order"),
    # path('cart/login/checkout', views.checkout,name="c

]

orders/models.py
from django.db import models
from accounts.models import Customer, Vendor
from datetime import datetime
from shop.models import Product
from django.utils.translation import gettext_lazy as _

now = datetime.now() # current date and time
year = int(now.strftime("%Y"))+24

class ShippingAddress(models.Model):
	"""
	Shipping address details for customers orders.
	"""
	STATUS_CHOICES = (
		("In Use", "IN USE"),
		("DeLeted" ,"DELETED")
	)
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	state = models.CharField(max_length=200, null=False)
	zipcode = models.CharField(max_length=200, null=False)
	created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
	active = models.BooleanField(default=False)
	country = models.CharField(max_length=200, null=False,default="")
	ref_code = models.CharField(max_length=200, null=True)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, null=False, default=STATUS_CHOICES[0][0])

	def __str__(self):
		return f'{self.address} - {self.customer}'


class ShippingPayment(models.Model):
	"""
	Shipping payment details for customers orders.
	"""
	MONTH_CHOICES = [(i, i) for i in range(1, 12)]
	YEAR_CHOICES = [(i, i) for i in range(1919, year)]
	YEAR_CHOICES.reverse()
	STATUS_CHOICES = (
		("In Use", "IN USE"),
		("DeLeted" ,"DELETED")
	)

	customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
	card_number= models.CharField(max_length=23, null=False)
	name_on_card = models.CharField(max_length=200, null=False)
	expiry_month = models.CharField(max_length=2,choices=MONTH_CHOICES, null=False)
	expiry_year = models.CharField(max_length=4, choices=YEAR_CHOICES, null=False)
	security_code = models.CharField(max_length=4, null=False)
	ref_code = models.CharField(max_length=200, null=True)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, null=False, default=STATUS_CHOICES[0][0])
	created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
	active = models.BooleanField(default=False)

	def __str__(self):
		return f'{self.card_number} - {self.customer}'



class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
	quantity = models.IntegerField(default=0)
	ref_code = models.CharField(max_length=200, null=True)
	is_ordered = models.BooleanField(default=False)
	created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
	date_ordered = models.DateTimeField(null=True)
	date_delivered = models.DateTimeField(null=True)
	delivered = models.BooleanField(default=False)

	def __str__(self):
		return f'{self.product.title} - {self.ref_code}'
	
	def get_total_price(self):
		return self.quantity * self.product.price


class Order(models.Model):
	ref_code = models.CharField(max_length=200, null=True)
	complete = models.BooleanField(default=False)
	vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, null=True)
	is_ordered = models.BooleanField(default=False)
	quantity = models.IntegerField(default=0)
	date_ordered = models.DateTimeField(auto_now=True)

	def get_address(self):
		return ShippingAddress.objects.filter(ref_code=self.ref_code).first()

	def get_payment(self):
		return ShippingPayment.objects.filter(ref_code=self.ref_code).first()

	def get_order_items(self):
		return OrderItem.objects.filter(ref_code=self.ref_code)

	def get_order_total(self):
		return sum([item.get_total_price() for item in self.orderitem_set.all()])

	def __str__(self):
		return f'{self.customer} - {self.ref_code}'

carts/views.py
import datetime
import json
import os
import random

from accounts.forms import *
from accounts.models import *
from orders.forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.forms import inlineformset_factory
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST, require_GET

from .decorators import *
from .models import *
from .utils import cartData, cookieCart, guestOrder
from .cart import Cart
from .forms import CartAddProductForm



User = get_user_model()

@require_GET
def send_messages(request):
	storage = messages.get_messages(request)
	storage.used = True
	stringed_messages = [str(item) for item in storage._loaded_messages]
	
	response = JsonResponse({"messages": stringed_messages, "Success": True})

	return response


def generateRefCode():	
	chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
	randomstr = ''.join((random.choice(chars)) for x in range(10))
	return randomstr

def cart(request):
	userPicture = 'user.png'
	if request.user.is_authenticated:
		if request.user.is_customer:
			userPicture = request.user.customer.profile_pic.url
		elif request.user.is_vendor:
			userPicture = request.user.vendor.profile_pic.url
	cart = Cart(request)
	cart_items = cart
	# print(dir(cart_items.cart),cart_items.cart.get('2'))
	total_items = cart.__len__()
	total_price = cart.get_total_price
	context = { 'total_price': total_price,'userPicture':userPicture,
				'cart_items':cart_items, 'total_items': total_items,
			  }
	return render(request, 'carts/cart.html', context)


@require_POST
def addItem(request):
	cart = Cart(request)
	product_id = int(request.POST.get("id"))
	product = get_object_or_404(Product, id=product_id)
	if cart.cart != {}:
		if str(product_id) not in cart.cart.keys():
			proposed_update = 1
		else:
			proposed_update = cart.cart[str(product_id)]['quantity'] + 1
		updated_request = request.POST.copy()
		updated_request.update({'quantity': proposed_update, "product": product})
		form = CartAddProductForm(updated_request)
	else:
		updated_request = request.POST.copy()
		updated_request.update({'quantity': 1, "product": product})
		form = CartAddProductForm(updated_request)
	# print(form.errors.as_json(),form.errors,dir(form))
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product,
				quantity=cd['quantity'],
				update_quantity=True
				)
	else:
		if "product" in form.errors.as_json():
			messages.warning(request,"Product doesn't exists")
		elif "Quantity":
			messages.add_message(request, messages.INFO, "You have maxed the quantity available for this product")
    # max quantity available 
    # min quantity - Shey you dey wine me ni
	cartqty = cart.__len__()
	total_price = f"{(cart.cart[str(product_id)]['quantity'] * product.regular_price):n}" if type(cart.cart[str(product_id)]['quantity']) == int else False
	updated_quantity = cart.cart[str(product_id)]['quantity'] if type(cart.cart[str(product_id)]['quantity']) == int else False
	response = JsonResponse({"qty": cartqty, "prc": f"{cart.get_total_price():n}", "Success": True, "total_price": total_price, "updated_quantity": updated_quantity })
	return response


@require_POST
def removeItem(request):
	cart = Cart(request)
	removeItem = False
	product_id = int(request.POST.get("id"))
	product = get_object_or_404(Product, id=product_id)
	if str(product_id) in cart.cart.keys():
		item = cart.cart[str(product_id)]['quantity']
		if item > 1:
			proposed_update = cart.cart[str(product_id)]['quantity'] - 1
			updated_request = request.POST.copy()
			updated_request.update({'quantity': proposed_update, "product": product})
			form = CartAddProductForm(updated_request)
			if form.is_valid():
				cd = form.cleaned_data
				cart.minus(product=product,
							quantity=cd['quantity'],)
			else:
				messages.add_message(request, messages.WARNING, "Error with quantity being removed!!!")
		else:
			cart.remove(product)
			removeItem = True
			print(cart.cart)
	cartqty = cart.__len__()
	try:
		total_price = f"{(cart.cart[str(product_id)]['quantity'] * product.regular_price):n}" if type(cart.cart[str(product_id)]['quantity']) == int else False
		updated_quantity = cart.cart[str(product_id)]['quantity'] if type(cart.cart[str(product_id)]['quantity']) == int else False
	except Exception as e:
		total_price = False
		updated_quantity = False
	response = JsonResponse({"qty": cartqty, "prc": f"{cart.get_total_price():n}", "removeItem": removeItem, "Success": True, "total_price": total_price, "updated_quantity": updated_quantity })
	return response


@require_POST
def removeAllItems(request):
	cart = Cart(request)
	product_id = int(request.POST.get("id"))
	product = get_object_or_404(Product, id=product_id)
	if str(product_id) in cart.cart.keys():
		cart.remove(product)
	cartqty = cart.__len__()
	response = JsonResponse({"qty": cartqty, "prc": f"{cart.get_total_price():n}", "Success": True })
	return response



@require_POST
def status(request):
	cart = Cart(request)
	cartqty = cart.__len__()
	response = JsonResponse({"qty": cartqty, "Success": True})
	return response


def checkout_authentication(request):
	if request.method == "POST":
		print(request.POST)
		form = AnonymousUserForm(request.POST)
		if form.is_valid():
			AnonymousUsers.objects.create(email=request.POST.get('email'))
			return redirect('carts:checkout_location')
	else:
		userPicture = 'user.png'
		if request.user.is_authenticated:
			if request.user.is_customer:
				userPicture = request.user.customer
			elif request.user.is_vendor:
				userPicture = request.user.vendor
		cart = Cart(request)
		cart_items = cart
		form = AnonymousUserForm()
		print(form)
		display_register = False if request.user.is_authenticated else True
		shipping = { "cost": 25, }
		order = { "discount": 0, "cost": sum( [shipping['cost'] , cart.get_total_price(),]) , "complete": True }
	context = {
				'cart_items':cart_items,
				'display_register':display_register,
				'form': form,
				'shipping': shipping,
				'order': order,
				'userPicture': userPicture
			}
	return render(request, 'carts/checkout/checkout_authentication.html', context)

def checkout_location(request):
	if request.method == "POST":
		print(request.POST)
	else:
		userPicture = 'user.png'
		if request.user.is_authenticated:
			if request.user.is_customer:
				userPicture = request.user.customer
			elif request.user.is_vendor:
				userPicture = request.user.vendor
		cart = Cart(request)
		cart_items = cart
		form = ShippingAddressForm()
		print(form)
		display_register = False if request.user.is_authenticated else True
		shipping = { "cost": 25, }
		order = { "discount": 0, "cost": sum( [shipping['cost'] , cart.get_total_price(),]) , "complete": True }
	context = {
				'cart_items':cart_items,
				'display_register':display_register,
				'form': form,
				'shipping': shipping,
				'order': order,
				'userPicture': userPicture
			}
	return render(request, 'carts/checkout/checkout_shipping.html', context)




@require_POST
def processOrder(request):
	if request.user.is_authenticated:
		print("Got Here Authenticated!")
		# customer = request.user.customer
		# cusorder, created = Order.objects.get_or_create(complete=False,customer=customer)
		# cusorder.complete = True
		# cusorder.is_ordered = True
		# cusorder.ref_code = generateRefCode()
		# orderIdv = cusorder.ref_code
		# cusorder.save()
		# orderItems = cusorder.orderitem_set.all()
		# for orderItem in orderItems:
		# 	orderItem.is_ordered=True
		# 	orderItem.save()
	else:
		print("Got Here Unauthenticated!")
		# 1. Get form data, user info, delivery, payment
		# 2. Get cart data
		# 3. Create anonymous user account
		# 4. Create Order for the vendor's item
		# 5. Process Payment




	# 	cookieData = cookieCart(request)
	# 	cartItems = cookieData['cartItems']
	# 	order = cookieData['order']
	# 	items = cookieData['items']
	# 	userData = json.loads(request.body)['form']
	# 	print(cookieCart)
	# 	print(cartItems)
	# 	print(order)
	# 	print(items)
	# 	print(userData)
	# 	print(items)
	# 	# Create user
	# 	print(userData)
	# 	username = userData['first_name'] + " " + userData['last_name']
	# 	password = userData['password']
	# 	print(username ,password)
	# 	new_user = User.objects.create_user(username= username,
	# 										email=userData['email'],
	# 										password=password,
	# 										first_name=userData['first_name'],
	# 										last_name=userData['last_name']
	# 										)
	# 	new_user.save()
	# 	messages.success(request, 'Account was created for ' + username)
	# 	print(new_user.id)
	# 	customer = Customer.objects.get(user=new_user.id)
	# 	print("here")
	# 	cusorder = Order.objects.create(
	# 										customer=customer,
	# 										complete=True,
	# 										is_ordered=True,
	# 										quantity=order['get_cart_items'],
	# 										ref_code=generateRefCode()
	# 										)
	# 	print('here2')
	# 	cusorder.save()
	# 	orderIdv = cusorder.ref_code
	# 	print(cusorder)
	# 	for item in items:
	# 		productitem = Product.objects.get(id=item['product']['id'])
	# 		print('here3')
	# 		print(productitem,cusorder,item['quantity'])
	# 		orderI=OrderItem.objects.create(
	# 										order=cusorder, 
	# 										product=productitem, 
	# 										quantity=item['quantity'], 
	# 										is_ordered=True,
	# 									)
	# 		print('here4')
	# 		orderI.save()
	# 	"""
	# Pass in order
	# Get a order
	# Get all vendors involved
	# Arrange the order by vendor Id
	# """
	# order = cusorder
	# print(order)
	# orderItems = order.get_cart_items()
	# print(orderItems)
	# allVendors = []
	# allVendorsId = set([])
	# sortedAllVendors = {}
	# print(allVendors,allVendorsId,sortedAllVendors)
	# for orderItem in orderItems:

carts/templates/carts/checkout/checkout.html
{% extends 'shop/main.html' %}
{% load static %}
{% load humanize %}
{% load debugger_tags %}
{% block content %}	

	<div class="container my-5">
		<div class="row">
			<div class="col text-center h1">
		  		<h1 class="h1">Checkout</h1>
			</div>
	  	</div>
	</div>

	<section class="no-overflow pt-0">
		<div class="container">
	  		<div class="row gutter-4 justify-content-between">
				<form id="regform" class="d-flex mx-auto" action="" method="POST" enctype="multipart/form-data">
					<div id="reg"  class="row align-items-end mb-2 col-lg-8">
						{% csrf_token %}	
						<!-- personal details -->
						<div class="row align-items-end mb-2">
							<div class="col-md-12">
								<h2 class="h3 mb-0"><span class="text-muted">01.</span> Personal Details</h2>
							</div>
							
						</div>
						<div class="liga">
						
							<div class="form-group">
								<label for="email">Email</label>
								{{ form.email }}
								<!-- <input type="text" class="form-control" id="companyName" placeholder=""> -->
							</div>
						</div>

						<!-- delivery address -->
						<div class="row align-items-end mb-2">
							<div class="col-md-12">
								<h2 class="h3 mb-0"><span class="text-muted">02.</span> Delivery Address</h2>
							</div>
						</div>
						<div class="row gutter-1 mb-6">
							<div class="form-group col-md-8">
								<label for="address">Address</label>
								<input type="text" class="form-control" id="address" name="address" placeholder="">
							</div>
							<div class="form-group col-md-4">
								<label for="city">City</label>
								<input type="text" class="form-control" id="city" name="city" placeholder="">
							</div>
							<div class="form-group col-md-4">
								<label for="state">State</label>
								<input type="text" class="form-control" id="state" name="state" placeholder="">
							</div>
							<div class="form-group col-md-4">
								<label for="postcode">Zipcode</label>
								<input type="text" class="form-control" id="zipcode" name="zipcode" placeholder="">
							</div>
							<div class="form-group col-md-4">
								<label for="country">Country</label>
								<input type="text" class="form-control" id="country" name="country" placeholder="">
							</div>
						</div>

						<!-- payment -->
						<div class="row align-items-end mb-2">
							<div class="col-md-12">
								<h2 class="h3 mb-0"><span class="text-muted">03.</span> Payment</h2>
							</div>
						</div>
						<div class="row gutter-1 mb-6">
							<div class="col-12 pb-1">
								<ul class="nav nav-tabs lavalamp" id="myTab" role="tablist">
									<li class="nav-item">
										<a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Credit Card</a>
									</li>
									<!-- <li class="nav-item">
										<a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">PayPal</a>
									</li> -->
								</ul>
							</div>
							<div class="col-12">
								<div class="tab-content" id="myTabContent">
									<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
										<div class="row gutter-1">
											<div class="form-group col-12">
												<div class="d-flex eyebrow">
													<div class="input-group-prepend">
														<span class="input-group-text" id="basic-addon1"><i class="icon-credit-card"></i></span>
													</div>
													<input type="tel" id="id_card_number" class="form-control eyebrow" placeholder="Card Number" name="card_number" aria-label="Username" aria-describedby="basic-addon1">
												</div>
											</div>
											<div class="form-group col-md-6">
												<label for="nameOnCard">Name on Card</label>
												<input type="text" class="form-control" id="nameOnCard" name="name_on_card" placeholder="">
											</div>
											<div class="form-group col-md-3">
												<label for="month">Month</label>
												<input type="date" class="form-control" name="date" id="month">
											</div>
											<div class="form-group col-md-3">
												<label for="cvv">CVV</label>
												<input type="password" class="form-control" id="cvv" name="cvv" placeholder="">
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>

					</div>
					<aside class="col-lg-4" id="orderDetails">
						<div class="row">

							<div class="col-12 mb-1" id="loginOpt">
								<div class=" d-flex bg-light p-3">
									<div class="col-8 pr-0">
										<h3 class="small">Already have an account?</h3>
									</div>
									<div class="text-right my-auto pl-0">
										<a href="{% url 'accounts:login' %}" class="underline eyebrow ml-2">Sign-In</a>
									</div>
								</div>
							</div>
							<div class="col-12 mb-1" id="signupOpt">
								<div class=" d-flex bg-light p-3">
									<div class="col-8 pr-0">
										<h3 class="small">Don't have an account? <span style="color: #63DE63;">Create one and come back to checkout</span></h3>
									</div>
									<div class="text-right my-auto pl-0">
										<a href="{% url 'accounts:customer_signup' %}" class="underline eyebrow ml-2">Sign-up</a>
									</div>
								</div>
							</div>
							<!-- order preview -->
							<div class="col-12">
								<div class="card card-data bg-light">
									<div class="card-header py-2 px-3">
										<div class="row align-items-center p-2">
											<div class="col">
												<h3 class="fs-18 mb-0">Your Cart</h3>
											</div>
											<div class="col text-right">
												<a href="{% url 'carts:cart' %}" class="underline eyebrow">Edit</a>
											</div>
										</div>
									</div>
									<div class="card-body">
										<ul class="list-group list-group-line">
											{% for item in cart_items %}
												<li class="list-group-item d-flex justify-content-between text-dark align-items-center">
												<img class="checkout-cart-item" src={% static item.product.image.first.image.url %} alt="Image">
												<span class="text-center p-1">{{ item.product.title }}</span>
												<span style="color: #63DE63;"class="p-1">x{{ item.quantity }}</span>
												<span>${{ item.total_price|floatformat:2|intcomma }}</span>
												</li>
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>

							<!-- order summary -->
							<div class="col-12 mt-1">
								<div class="card card-data bg-light">
									<div class="card-header py-2 px-3">
										<div class="row align-items-center p-2">
											<div class="col">
												<h3 class="fs-18 mb-0">Order Summary</h3>
											</div>
										</div>
									</div>
									
									<div class="card-body">
										<ul class="list-group list-group-minimal">
											<li class="list-group-item d-flex justify-content-between align-items-center py-1">
												Subtotal
												<span>${{cart_items.get_total_price}}</span>
											</li>
											<li class="list-group-item d-flex justify-content-between align-items-center py-1">
												Shipping<span>${{ shipping.cost }}</span>
											</li>
											<li class="list-group-item d-flex justify-content-between align-items-center py-1">
											Discount
											<span>-{{order.discount}}%</span>
											</li>
										</ul>
									</div>
									<div class="card-footer py-1">
										<ul class="list-group list-group-minimal">
											<li class="list-group-item d-flex justify-content-between align-items-center text-dark fs-18">
												Total<span>${{order.cost}}</span>
											</li>
										</ul>
									</div>
								</div>
							</div>

							<!-- place order -->
							<div class="col-12 mt-1 eyebrow">
								<a id="placeOrder" class="btn btn-primary btn-lg btn-block eyebrow text-white">Place Order</a>
							</div>

						</div>
					</aside>
				</form>
			</div>
		</div>
	</section>
		
{% endblock %}