Hustle_24/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
# from rest_framework import routers
from shop import views as shop_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from watched_products import views as watched_products_views




# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),

    path('', include('user_sessions.urls', namespace='user_sessions')),

    path('', include('shop.urls', namespace='shop')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('carts.urls', namespace='carts')),
    path('', include('watched_products.urls', namespace='watched_products')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path('register', views.registerCustomer, name="register"),
    path('register/vendor/', views.registerVendor, name="register-vendor"),
    
    path('login/', views.loginPage, name='login'),
    # path('login/', views.LoginView.as_view(), name='login'),

    path('logout/', views.logoutUser, name='logout'),

    path('customer/<customer>', views.customerPage, name='customer'),
    path('vendor/<vendor>', views.vendorPage, name='vendor'),
    path('account/', views.accountSettings, name='account'),

    path("password_reset", views.password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html", success_url=reverse_lazy(
        'accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),      
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers
# from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt import views as jwt_views



app_name= 'api'
router = routers.DefaultRouter()
router.register(r'Products', ListProductsView)
router.register(r'Categories', CategoriesView)
router.register(r'Product-photos', ProductImageView)
router.register(r'Reviews', ReviewsView)
router.register(r'Shop', ShopView)
router.register(r'Specifications', ProductSpecificationView)
# router.register(r'Registration', RegistrationView)


urlpatterns = [
	path('', include(router.urls)),
	path('sign-up/', RegistrationView.as_view(), name='register'),
	path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]
# urlpatterns+= router.urls

carts/urls.py
from django.urls import path

from . import views

app_name ='carts'

urlpatterns = [
    path('cart', views.cart,name="cart"),

    path('cart/add', views.addItem,name="add"),
    path('cart/remove', views.removeItem,name="remove"),
    path('cart/status', views.status, name="status"),
    path('cart/remove-all', views.removeAllItems, name="removeAll"),

    # path('cart/messages', views.send_messages, name="messages"),
    path('cart/checkout/auth', views.checkout_authentication,name="checkout_auth"),
    path('cart/checkout/location', views.checkout_location,name="checkout_location"),

    path('cart/process-order', views.processOrder,name="process-order"),
    # path('cart/login/checkout', views.checkout,name="c

]

shop/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import  views

app_name= 'shop'

urlpatterns = [
    path('', views.home,name="home"),
    # path('shop/<shop>', views.shop, name='shop'),
    path('<shop>/product/<ref_code>/<title>/', views.productDetail, name='product'),    
    path('<shop>/product/add', views.addProduct, name='addProduct'),
    path('<shop>/<product>/<id>/edit/', views.editProduct, name='editProduct'), 
    path('updatephoto', views.deleteProductImage,name="updatephoto"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import *


class AddProductForm(ModelForm):
	class Meta:
		model = Product
		fields = '__all__'

	def __init__(self, *args, **kwargs):
		super(AddProductForm, self).__init__(*args, **kwargs)
		self.fields['stock'].widget.attrs.update({'type': 'number',
			'onkeypress': 'return isNumberKey(event)', 'min': 1})
		for field in self.fields.keys():
			self.fields[field].widget.attrs.update({'class': 'form-control'})
		self.fields['description'].widget.attrs['class'] = 'form-control textarea'
		self.fields['price'].widget.attrs.update({'type': 'price',
			'placeholder': 'Type a number & click outside', 'min': 0.00,
			'onkeypress': 'return isNumberKey(event)'})

shop/views.py
import ast
import json
import locale
import re
from dis import dis

from accounts.models import *
from carts.models import *
from carts.utils import *
# Create your views here.
from django.contrib.auth import get_user_model
# from django.forms import inlineformset_factory
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth import authenticate, login, logout
# from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
# from permissions import *
# from rest_framework import renderers, viewsets
# from rest_framework.response import Response

from .decorators import *
from .forms import *
from .models import *

locale.setlocale(locale.LC_ALL, '')
deletedProductImages = set([])


def generate_ref_code():
	chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
	random_str = ''.join((random.choice(chars)) for _ in range(10))
	return random_str


def home(request, category_slug=None):
	userPicture = 'user.png'
	if request.user.is_authenticated:
		if request.user.is_customer:
			userPicture = request.user.customer.profile_pic.url
		elif request.user.is_vendor:
			userPicture = request.user.vendor.profile_pic.url
	user = request.user
	userId = request.user.id
	ref_code = generateRefCode
	# products = Product.objects.filter(is_active=True)
	products = Product.objects.prefetch_related("image").filter(is_active=True)
	data = cartData(request)
	cart_data = data['cart_data']
	cart_items = data['cart_items']
	# print(cart_data.ref_code,1111)
	show = True
	for group in request.user.groups.all():
		print(group)
		if 'Vendor' == str(group):
			show = False
	# print(products.productimages)
	# products = list(products)
	productsdict = []
	for product in products:
		title = product.title
		price = product.regular_price
		pid = product.id
		description = product.description
		link = product.get_absolute_url
		image = product.image.first().image.url
		productsdict.append({'title': title, 'price': price,
							'description': description, 'link': link, 'image': image, 'id': pid})
	context = {'data': productsdict,
			   'show': show,
			   'id': userId,
			   'user': user,
			   'cart_data': cart_data,
			   'userPicture': userPicture
			   }
	return render(request, 'shop/index.html', context)


def productDetail(request, title,ref_code,shop):
	userPicture = 'user.png'
	if request.user.is_authenticated:
		if request.user.is_customer:
			userPicture = request.user.customer.profile_pic.url
		elif request.user.is_vendor:
			userPicture = request.user.vendor.profile_pic.url
	product = Product.objects.filter(ref_code=ref_code).get()
	store = product.get_shop
	price = f'{product.regular_price:n}'
	images = product.image.filter(is_feature=True).all()
	mainimage = product.image.filter(is_feature=False).first().image.url
	productsdict = []
	print(product.get_shop.vendor_id, Shop.objects.get(id=store.id).products.all())
	data = cartData(request)
	cart_data = data['cart_data']
	cart_items = data['cart_items']
	for image in images.all():
		productsdict.append({'image': str('images/' + str(image))})
	context = {'userPicture': userPicture, 'product': product, 'price': price, 'store': store,
			   'productsdict': productsdict, 'mainimage': mainimage, 'cartItems': cart_items, }
	return render(request, 'shop/product.html', context)


# @unauthenticated_user
@login_required(login_url='login')
@with_usertype(allowed_roles=['Vendor'])
def addProduct(request, shop):
	form = AddProductForm()
	vendor = request.user.vendor
	products = Shop.objects.get(vendor=vendor.id).products.all()
	shop = Shop.objects.get(vendor=vendor)
	print(shop.products.all())
	productsId = [product.id for product in products]
	reviews = []
	for x in productsId:
		z = ProductReview.objects.filter(product=x)
		for a in z:
			reviews.append(a)
	# print(shop.products)
	if request.method == "POST" and request.POST.get("form_type") == 'addProduct':
		title = request.POST.get('title')
		categories = request.POST.getlist('categories')
		brand = request.POST.get('brand')
		description = request.POST.get('description')
		stock = request.POST.get('stock')
		price = float((request.POST.get('price')[1:]).replace(',', ''))
		discount = float((request.POST.get('discount')[1:]).replace(',', ''))
		image = request.FILES.get('choose-file')
		productImages = request.FILES.getlist('productImages')
		create_product = Product.objects.create(
			title=title,
			brand=brand,
			description=description,
			price=price,
			discount_price=discount,
			image=image,
			available=True,
			stock=stock,
			is_featured=True
		)
		for category in categories:
			# Check if string is empty or contain spaces only
			if not re.search("^\s*$", category):
				category_slug = category.replace(" ", "-")
				create_category = Category.objects.create(
					name=category, slug=category_slug)
				create_category.save()
				create_product.category.add(create_category)
		for image in productImages:
			create_ProductImage = ProductImage.objects.create(images=image)
			create_ProductImage.save()
			create_product.productimages.add(create_ProductImage)
		create_product.save()
		shop.products.add(create_product)
		shop.save()
	context = {'form': form, }
	return render(request, 'shop/product-add.html', context)


# @unauthenticated_user
@login_required(login_url='login')
@with_usertype(allowed_roles=['Vendor'])
def editProduct(request, shop, product, id):
	product = Product.objects.get(id=int(id))
	form = AddProductForm(instance=product)
	productimage = product.image.url
	productimages = product.productimages.all()
	categories = []
	for category in product.category.all():
		categories.append(category.name)
	for x in productimages:
		print(x.images.url)
	# vendor = request.user.vendor
	# products = Shop.objects.get(vendor=vendor.id).products.all()
	# shop = Shop.objects.get(vendor=vendor)
	# print(shop.products.all())
	# productsId = [ product.id for product in products]
	# reviews = []
	# for x in productsId:
	# 	z = ProductReview.objects.filter(product=x)
	# 	for a in z:
	# 		reviews.append(a)
	# # print(shop.products)
	if request.method == "POST" and request.POST.get("form_type") == 'editProduct':
		# print(request.POST, deletedProductImages,22222333)
		title = request.POST.get('title')
		categoriesRecieved = request.POST.getlist('categories')
		brand = request.POST.get('brand')
		description = request.POST.get('description')
		stock = request.POST.get('stock')
		# Price
		price = request.POST.get('price')
		non_decimalPrice = re.compile(r'[^\d.]+')
		price = float(non_decimalPrice.sub('', price))
		# Discount
		discount = request.POST.get('discount')
		print(discount)
		non_decimalDiscount = re.compile(r'[^\d.]+')
		discount = float(non_decimalDiscount.sub('', discount))

		image = request.FILES.get('choose-file')
		productImages = request.FILES.getlist('productImages')

		print(title, categories, brand, description,
			  stock, price, discount, image, productImages)
		product.title = title
		product.brand = brand
		product.description = description
		product.price = price
		product.discount = discount

		if image == None:
			pass
		else:
			product.image = image
	# for itemCategory in categoriesRecieved:
	# 	if itemCategory in categories:
	# 		pass
	# 	else

	# for imageItem in deletedProductImages:
	# 	productExtraImage

	# for category in categories:
	# 	# Check if string is empty or contain spaces only
	# 	if not re.search("^\s*$", category):
	# 		category_slug = category.replace(" ", "-")
	# 		create_category = Category.objects.create(name=category,slug=category_slug)
	# 		create_category.save()
	# 		create_product.category.add(create_category)
	# create_product = Product.objects.create(
	# 			title=title,
	# 			brand=brand,
	# 			description=description,
	# 			price=price,
	# 			discount_price=discount,
	# 			image=image,
	# 			available=True,
	# 			stock=stock,
	# 			is_featured=True
	# 		)
	# 	for category in categories:
	# 		# Check if string is empty or contain spaces only
	# 		if not re.search("^\s*$", category):
	# 			category_slug = category.replace(" ", "-")
	# 			create_category = Category.objects.create(name=category,slug=category_slug)
	# 			create_category.save()
	# 			create_product.category.add(create_category)
	# 	for image in productImages:
	# 		create_ProductImage = ProductImage.objects.create(images=image)
	# 		create_ProductImage.save()
	# 		create_product.productimages.add(create_ProductImage)
	# 	create_product.save()
	# 	shop.products.add(create_product)
	# 	shop.save()
	deletedProductImages.clear()
	context = {'form': form, 'id': id, 'productimage': productimage,
			   'categories': categories, 'productimages': productimages, }
	return render(request, 'shop/product-edit.html', context)


# @unauthenticated_user
@login_required(login_url='login')
@with_usertype(allowed_roles=['Vendor'])
def deleteProductImage(request):
	data = request.POST['motif']
	data = ast.literal_eval(data)
	for x in data:
		deletedProductImages.add(x)
	return JsonResponse({'success': True}, status=200)

shop/templates/shop/index.html
{% extends 'shop/main.html' %}
{% load humanize %}
{% load product_utils %}
{% block title %}Home{% endblock %}
{% load static %}

{% block content %}	
	<div class="products w-80 mx-auto">

		{% for product in data %}
			<div class="product-card card" >
				<div class="img-container">
					<a href="{{product.link}}" class="">
						<img class="card-img-top product-img" src={% static product.image %} alt={{product.image}}>
					</a>
				</div>
				<div class="d-flex border">
					<div class="px-1 small col-6 text-left border-right" style="padding: 5px 0;">
						<a href="{{product.link}}" class="">
							<h5 class="fs-16 text-truncate">{{ product.title }}</h5>
							<p class="card-text m-0 ">${{ product.price|floatformat:2|intcomma }}</p>
						</a>
					</div>
					{% check_user_wishlist request product.id as check %}
					<div data-product={{product.id}} data-action={{ check.action }} data-quantity={{product.stock}} data-price={{product.price}} class="underline col-3 border-right mx-auto d-flex justify-content-center update-watch-list {{ check.color}}" style="padding: 5px 0;">
						<span class="icon icon-heart-o animated "></span>
					</div>

					<div data-product={{product.id}} data-url={% url "carts:add" %} data-action="add" class="add underline update-cart col-3 mx-auto d-flex justify-content-center cart-add">
						<span data-product={{product.id}} data-url={% url "carts:add" %} data-action="add" class="icon icon-add_shopping_cart"></span>
					</div>
				</div>
			</div>
		{% endfor %}
		{# <h1>{% check_user_wishlist request 1 %}</h1> #}
	</div>
{% endblock %}

shop/templates/shop/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{% block title %}{% endblock %} | H24</title>

		<link
			rel="apple-touch-icon"
			sizes="180x180"
			href="{% static '/favicon_io/apple-touch-icon.png' %}"
		/>
		<link
			rel="icon"
			type="image/png"
			sizes="32x32"
			href="{% static '/favicon_io/favicon-32x32.png' %}"
		/>
		<link
			rel="icon"
			type="image/png"
			sizes="16x16"
			href="{% static '/favicon_io/favicon-16x16.png' %}"
		/>
		<link rel="manifest" href="/site.webmanifest" />
		<link
			rel="stylesheet"
			href="{% static '/bootstrap/css/bootstrap-grid.css' %}"
		/>
		<link
			rel="stylesheet"
			href="{% static '/bootstrap/css/bootstrap-grid.min.css' %}"
		/>
		<link
			rel="stylesheet"
			href="{% static '/bootstrap/css/bootstrap-reboot.css' %}"
		/>
		<link
			rel="stylesheet"
			href="{% static '/bootstrap/css/bootstrap-reboot.min.css' %}"
		/>
		<link
			rel="stylesheet"
			href="{% static '/bootstrap/css/bootstrap.css' %}"
		/>
		<link
			rel="stylesheet"
			href="{% static '/bootstrap/css/bootstrap.min.css' %}"
		/>
		<link rel="stylesheet" href="{% static '/css/vendor.css' %}" />
		<link rel="stylesheet" href="{% static '/css/style.css' %}" />
		<link rel="stylesheet" href="{% static '/icomoon/style.css' %}" />
		<link
			rel="stylesheet"
			href="{% static '/icomoon/demo-files/demo.css' %}"
		/>
		<link rel="stylesheet" href="{% static '/css/h24.css' %}" />

		<style>
			.sdiv {
				padding-top: 20px !important;
			}
		</style>
		{% block extrascripts %}
		<script>
			var user = "{{request.user}}";
			var user_is_vendor = "{{request.user.is_vendor}}";
			var cart_url = "{% url 'carts:cart' %}";

			function getToken(name) {
				let cookieValue = null;
				if (document.cookie && document.cookie !== "") {
					const cookies = document.cookie.split(";");
					for (let i = 0; i < cookies.length; i++) {
						const cookie = cookies[i].trim();
						// Does this cookie string begin with the name we want?
						if (
							cookie.substring(0, name.length + 1) ===
							name + "="
						) {
							console.log("heres 1233");
							cookieValue = decodeURIComponent(
								cookie.substring(name.length + 1)
							);
							break;
						}
					}
				}
				return cookieValue;
			}
			const csrftoken = getToken("csrftoken");

			function getCookie(name) {
				// Split cookie string and get all individual name=value pairs in an array
				var cookieArr = document.cookie.split(";");

				for (var i = 0; i < cookieArr.length; i++) {
					var cookiePair = cookieArr[i].split("=");

					/* Removing whitespace at the beginning of the cookie name
				and compare it with the given string */
					if (name == cookiePair[0].trim()) {
						// Decode the cookie value and return
						return decodeURIComponent(cookiePair[1]);
					}
				}
				return null;
			}
			var cart = JSON.parse(getCookie("cart"));

			if (cart == undefined) {
				cart = {};
				console.log("Cart was created");
				document.cookie =
					"cart=" + JSON.stringify(cart) + ";domain=;path=/";
			}

			var watchlist = JSON.parse(getCookie("watchlist"));

			if (watchlist == undefined) {
				watchlist = {};
				console.log("watchlist was created");
				document.cookie =
					"watchlist=" +
					JSON.stringify(watchlist) +
					";domain=;path=/";
			}

			console.log("cart:", cart);
			console.log("watchlist:", watchlist);
		</script>
		{% endblock %}
	</head>
	<body>
		{% include 'shop/navbar.html' %}
		<div
			class="mb-5 sdiv mb-auto overflow-hidden"
			style="min-height: 100vh"
		>
			{% block content %} {% endblock %}
		</div>

		<hr />
		{% block extra_js %}
		<footer class="note">Copyright © Hustle 24</footer>
		<script src="{% static '/bootstrap/js/bootstrap.bundle.js' %}"></script>
		<script src="{% static '/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static '/bootstrap/js/bootstrap.js' %}"></script>
		<script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
		<script src="{% static '/js/vendor.min.js' %}"></script>
		<script src="{% static '/js/app.js' %}"></script>
		<script src="{% static '/js/cart.js' %}"></script>
		<script
			src="{% static '/js/cart2.js' %}"
			type="text/javascript"
		></script>
		<script
			src="{% static '/js/checkout.js' %}"
			type="text/javascript"
		></script>
		{% endblock %}
	</body>
</html>

shop/templates/shop/messages.html
<div id="messagesContainer">
</div>

shop/templates/shop/navbar.html
{% load humanize %} {% load static %}

<nav class="navbar-expand-lg fixed-top p-0">
	<div class="navbar d-flex">
		<div class="navbar-header py-2 col-5">
			<a href="{% url 'shop:home' %}" class="navbar-brand px-lg-2 px-1">
				<img src="{% static '/images/h24.png' %}" alt="Logo" />
			</a>
		</div>

		<div
			class="navbar-brand ml-lg-5 order-lg-last order-0 py-lg-1 px-1 d-flex"
		>
			<a
				href="javascript:void(0);"
				class="icon-search-link"
				onclick="showsearch()"
				style="padding: 0 8px"
			>
				<div
					class="order-lg-last order-0 d-flex align-items-start account"
				>
					<span class="icon icon-search" aria-hidden="true"></span>
				</div>
			</a>
			<a
				href="{% url 'accounts:register-vendor' %}"
				id="navSetupShop"
				class="signLinks invisible"
			>
				<div
					class="order-lg-last order-0 d-flex align-items-start account px-lg-2 px-1"
				>
					<p class="eyebrow">Set up Shop</p>
					<span
						class="icon icon-store_mall_directory"
						style="color: #63de63"
					></span>
				</div>
			</a>

			{% if request.user.is_authenticated %}
			<!-- User is logged in -->
			{% else %}
			<a href="{% url 'accounts:login' %}" class="signLinks">
				<div
					class="order-lg-last order-0 d-flex align-items-start account px-lg-2 px-1"
				>
					<small class="icon nav-link eyebrow">Sign In</small>
				</div>
			</a>
			<a href="{% url 'accounts:customer_signup' %}" class="signLinks">
				<div
					class="order-lg-last order-0 d-flex align-items-start account px-lg-2 px-1"
				>
					<small class="icon nav-link eyebrow">Sign Up</small>
				</div>
			</a>
			{% endif %}

			<a href="{% url 'carts:cart' %}">
				<div
					class="order-lg-last order-0 d-flex align-items-start account px-lg-2 px-1"
				>
					<span class="icon icon-shopping-cart" id="main-cart"></span>
					<div>
						<p id="cart-total" class="eyebrow text-truncate">
							{{ cart_data.quantity|intcomma }}
						</p>
					</div>
				</div>
			</a>

			<a href="{% url 'accounts:customer' request.user %}" id="user">
				<div
					class="order-lg-last order-0 d-flex align-items-start account px-lg-2 px-1"
				>
					<div class="image-cropper d-flex">
						<img
							class="profile-pic"
							src="{% static userPicture %}"
							alt="User Profile"
						/>
					</div>
				</div>
			</a>

			<a
				id="subMenu"
				class="collapsed"
				data-toggle="collapse"
				href="#collapseThree"
				aria-expanded="false"
				aria-controls="collapseThree"
			>
				<div
					class="order-lg-last order-0 d-flex align-items-start account px-lg-2 px-1"
				>
					<div class="menu-container">
						<div class="menu_icon">
							<span class="one"></span>
							<span class="two"></span>
							<span class="three"></span>
						</div>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div class="shortsearch">
		<div id="myLinks" class="mx-auto">
			<div class="card-body d-flex">
				<input
					type="search"
					name="search"
					class="form-control mr-1"
					placeholder="Search for products shops or vendors"
				/>
				<button
					type="button"
					class="btn btn-default ml-1"
					data-dismiss="modal"
				>
					Close
				</button>
			</div>
		</div>
	</div>

	<div
		id="accordion2"
		role="tablist"
		style="
			background-color: #b7f73c;
			background-image: url({% static 'images/levi-stute-mFF39sOZSgM-unsplash.jpg' %});
			background-position: center;
			background-size: cover;
		"
	>
		<!-- Content goes here -->
	</div>

	<div class="card">
		<div
			id="collapseThree"
			class="collapse"
			role="tabpanel"
			aria-labelledby="headingThree"
			data-parent="#accordion2"
		>
			<ul class="card-body menu">
				{% if request.user.is_authenticated %}
				<li class="py-1">
					<a href="{% url 'accounts:logout' %}">
						<div class="d-flex invert nav-link">
							<p class="eyebrow text-center my-auto">Sign out</p>
							<span
								class="icon icon-sign-out ml-auto"
								style="color: #63de63"
							></span>
						</div>
					</a>
				</li>
				{% if request.user.is_vendor %}
				<li class="py-1">
					<a href="{% url 'accounts:vendor' request.user %}">
						<div class="d-flex invert nav-link">
							<p class="eyebrow text-center my-auto">Shop</p>
							<span
								class="icon icon-store_mall_directory ml-auto"
								style="color: #63de63"
							></span>
						</div>
					</a>
				</li>
				{% endif %} {% else %}
				<a href="{% url 'accounts:login' %}">
					<li class="py-1">
						<small class="icon nav-link eyebrow invert"
							>Sign In</small
						>
					</li>
				</a>
				<a href="{% url 'accounts:register' %}">
					<li class="py-1">
						<small class="icon nav-link eyebrow invert"
							>Sign Up</small
						>
					</li>
				</a>
				<li class="py-1">
					<a href="{% url 'accounts:register-vendor' %}">
						<div class="d-flex invert nav-link">
							<p class="eyebrow text-center my-auto">
								Set up Shop
							</p>
							<span
								class="icon icon-store_mall_directory"
								style="color: #63de63"
							></span>
						</div>
					</a>
				</li>
				{% endif %}
			</ul>
		</div>
	</div>

	<div class="navbar-body p-1 h6 my-0 bg-light d-flex" id="setUpShop">
		<span class="icon icon-close col-sm-1 p-0" id="closeSetUpShop"></span>
		<div class="col text-right d-flex justify-content-end">
			<p class="eyebrow my-auto" style="font-size: 11px">
				Want to sell something?
			</p>
			<a
				href="{% url 'accounts:register-vendor' %}"
				class="btn btn-link btn-sm"
			>
				<small>Set up Shop</small>
				<span
					class="icon icon-store_mall_directory"
					style="color: #63de63"
				></span>
			</a>
		</div>
	</div>

	<script>
		// Dynamically handle the visibility of the "Set up Shop" link
		var setUpShop = document.getElementById("setUpShop");
		var navSetUpShop = document.getElementById("navSetupShop");
		var closeSetUpShop = document.getElementById("closeSetUpShop");
		var userProfile = document.getElementById("user");

		// Assuming the variables user_is_vendor and user are passed from Django templates
		var user_is_vendor = "{{ request.user.is_vendor }}";
		var user = "{{ request.user.username }}";

		if (user_is_vendor === "True") {
			setUpShop.remove();
			navSetUpShop.remove();
		}
		if (user === "AnonymousUser") {
			userProfile.remove();
		}
		if (getCookie("shop") === "true") {
			setUpShop.remove();
			navSetUpShop.classList.toggle("invisible");
		}

		var icon = document.querySelector(".menu_icon");
		icon.addEventListener("click", () => {
			icon.classList.toggle("clicked");
		});

		const header = document.querySelector("nav");
		let prev = window.pageYOffset;

		window.addEventListener("scroll", function () {
			let current = window.pageYOffset;
			if (prev < current) {
				header.classList.add("disappear");
			} else {
				header.classList.remove("disappear");
			}
			prev = current;
		});
	</script>
</nav>